### ISSUE TITLE
No available formula with the name "coreutils".

### ISSUE THREAD

**Issue by tedd666** [4ndr34z/shells#2]
Warning: No available formula with the name "coreutils".
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching for a previously deleted formula (in the last month)...
Error: No previously deleted formula found.
==> Searching taps on GitHub...

**Comment by tedd666** [comment]
yes, no formula fond also

**Comment by tedd666** [comment]
> Seen this?
> https://stackoverflow.com/questions/37635486/why-cant-brew-find-a-specific-known-formula

yeah 
I tried all I could but didn't work

**Comment by tedd666** [comment]
Error: No formulae or casks found for "coreutils".

**Comment by 4ndr34z** [comment]
Sorry. Never had these problems, so haven’t had a deep dive in home brew troubleshooting. Tried "brew doctor" or reinstall brew?

**Comment by 4ndr34z** [comment]
Did you ever get this sorted?
