### ISSUE TITLE
Xonsh shell support

### ISSUE THREAD

**Issue by anki-code** [4ndr34z/shells#4]
Hi!
It will be cool to support [xonsh shell](https://xon.sh) as well.
Thanks!

**Comment by 4ndr34z** [comment]
HiWill look into it. Wasn’t aware of Xonsh. Cool! Thanks😊Med vennlig hilsen / Kind regardsAndreas Finstad22. mar. 2023 kl. 17:46 skrev Andy Kipp ***@***.***>:﻿
Hi!
It will be cool to support xonsh shell as well.
Thanks!
