### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by throwawaya609** [4ndr34z/shells#6]
![image](https://github.com/4ndr34z/shells/assets/109557965/57a80c5b-18c1-45a7-85eb-7978a8652d4d)

**Comment by 4ndr34z** [comment]
Hi. This is strange. It is during the pull request. Have to be a network issue or maybe firewall/Antivirus blocking it?

**Comment by 4ndr34z** [comment]
Cannot see that this error has anything to do with the script itself, so closing it
