### ISSUE TITLE
Problem whit Ngrok 

### ISSUE THREAD

**Issue by MarKaliGG** [4ndr34z/shells#7]
When i press n the script make the first session , i can see it on my ngrok dashboard, btw still say ngrok not work. How can i fix this error ? I dont want update my ngrok account , is it possibile?  Thank u for all the support!

i have to do another .yaml file whit us region ? Im from italy

**Comment by 4ndr34z** [comment]
Hi. I’ll look into it. I only have the free version. Try killing everything and start ngrok from Shellz?
